import type { ReferenceMaterial } from "../lib/specs/schema";

/**
 * Test fixture: Vincent Ave kitchen WITH 3 designer-supplied reference images.
 *
 * Re-exports the existing Vincent Ave kitchen spec/context/description and
 * adds a references array. The storage paths are stubs — this fixture is
 * only used for PROMPT review (Sonnet → Opus), never for an actual Gemini
 * render, so the files don't need to exist on disk.
 *
 * Purpose in 2.5: test whether Opus catches reference-handling issues in
 * the generated prompt. The prompt should describe what each reference is
 * and how Gemini should use it (a REFERENCE IMAGES: block, generated by
 * buildRenderPromptRequest when `references` is passed).
 */

export {
  vincentAveContext,
  vincentAveKitchenSpec,
  vincentAveKitchenBasePhotoDescription,
} from "./vincent-ave-kitchen";

export const vincentAveKitchenWithRefsReferences: ReferenceMaterial[] = [
  {
    label: "zellige handmade sample",
    material_type: "backsplash",
    storage_path: "property-references/vincent-ave/zellige-sample.jpg",
    mime_type: "image/jpeg",
  },
  {
    label: "unlacquered brass patina reference",
    material_type: "hardware",
    storage_path: "property-references/vincent-ave/brass-patina.jpg",
    mime_type: "image/jpeg",
  },
  {
    label: "white oak LVP plank sample",
    material_type: "flooring",
    storage_path: "property-references/vincent-ave/white-oak-lvp.jpg",
    mime_type: "image/jpeg",
  },
];
